# Generated by Django 4.0.4 on 2022-11-12 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Prode', '0003_fase_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EquipoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prode.equipos')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prode.partido')),
            ],
        ),
    ]
