# Generated by Django 4.0.4 on 2022-11-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prode', '0004_partido_fecha_equipopartido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipopartido',
            options={'verbose_name': 'Equipo por partido', 'verbose_name_plural': 'Equipos por partido'},
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_goles', models.IntegerField(default=0)),
                ('equipo_partido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prode.equipopartido')),
            ],
            options={
                'verbose_name': 'Resultado final',
                'verbose_name_plural': 'Resultados finales',
            },
        ),
    ]
